
 const AutoCompleteItems = [
   "2 Handed Kettlebell Swing",
 "Arnold Shoulder Press",
 "Barbell Lunges",
 "Axe Hold",
 "Barbell Ab Rollout",
 "Barbell Triceps Extension",
 "Bear Walk",
 "Bench Press",
 "Bear Walk",
 "Benchpress Dumbbells",
 "Bench Press Narrow Grip",
 "Bent Over Barbell Row",
 "Bent High Pulls",
 "Bent-over Lateral Raises",
 "Bentover Dumbbell Rows",
 "Bent Over Rowing",
 "Bent Over Rowing Reverse",
 "Biceps Curls With Barbell",
 "Power Clean",
 "Biceps Curls With Dumbbell",
 "Bulgarian Split Squat",
 "Butterfly Reverse",
 "Close-grip Bench Press",
 "Crunches",
 "Decline Pushups",
 "Dips Between Two Benches",
 "Dumbbells on Scott Machine",
 "Fly With Cable",
 "Fly With Dumbbells",
 "Glute Bridge",
 "Hand Grip",
 "High Knees",
 "Incline Bench Press",
 "Incline Pushups",
 "Lateral Raises on Cable, One Armed",
 "Leg Curls (standing)",
 "Leg Raises, Lying",
 "L Hold",
 "Military Press",
 "Overhead Squat",
 "Plank",
 "Pull-ups",
 "Rear Delt Raises",
 "Romanian Deadlift",
 "Run",
 "Shoulder Press, Dumbbells",
 "Shrugs, Dumbbells",
 "Biceps Curls With SZ-bar",
 "Burpees",
 "Cable External Rotation",
 "Chin-ups",
 "Crunches on Machine",
 "Deadlifts",
 "Diagonal Shoulder Press",
 "Dumbbell Incline Curl",
 "Extenseurs - Face",
 "French Press (skullcrusher) SZ-bar",
 "Front Squats",
 "Hammercurls on Cable",
 "High Pull",
 "Incline Dumbbell Row",
 "Lateral Raises",
 "Leg Curls (laying)",
 "Leg Presses (wide)",
 "Leverage Machine Iso Row",
 "Lying Rotator Cuff Exercise",
 "Overhand Cable Curl",
 "Pike Push Ups",
 "Prone Scapular Retraction - Arms at Side",
 "Biceps Curl With Cable",
 "Braced Squat",
 "Cable Cross-over",
 "Close-grip Lat Pull Down",
 "Crunches With Legs Up",
 "Decline Bench Press Dumbbell",
 "Dumbbell Concentration Curl",
 "Dumbbell Lunges Walking",
 "Flutter Kicks",
 "Fly With Dumbbells, Decline Bench",
 "Hammercurls",
 "High Knee Jumps",
 "Hyperextensions",
 "Incline Plank With Alternate Floor Touch",
 "Kettlebell Swings",
 "Lat Pull Down (Leaning Back)",
 "Leg Presses (narrow)",
 "Leverage Machine Chest Press",
 "Body-Ups",
 "Butterfly Narrow Grip",
 "Calf Press Using Leg Press Machine",
 "Cross-Bench Dumbbell Pullovers",
 "Deadhang",
 "Dips",
 "Dumbbell Goblet Squat",
 "Facepull",
 "Front Raises",
 "Good Mornings",
 "Hanging Leg Raises",
 "Hollow Hold",
 "Incline Dumbbell Press",
 "Jogging",
 "Lat Pull Down (Straight Back)",
 "Leg Extension",
 "Leg Raises, Standing",
 "Low Box Squat - Wide Stance",
 "Military Press",
 "Perfect Push Up",
 "Butterfly",
 "Cable Woodchoppers",
 "Calf Raises on Hackenschmitt Machine",
 "Crunches With Cable",
 "Decline Bench Press Barbell",
 "Deficit Deadlift",
 "Dumbbell Lunges Standing",
 "Dumbbell Triceps Extension",
 "French Press (skullcrusher) Dumbbells",
 "Full Sit Outs",
 "Hercules Pillars",
 "Hip Raise, Lying",
 "Incline Dumbbell Flye",
 "Isometric Wipers",
 "Lateral-to-Front Raises",
 "Leg Curls (sitting)",
 "Leg Press on Hackenschmidt Machine",
 "Long-Pulley (low Row)",
 "MGM Machine",
 "Long-Pulley, Narrow",
 "Negative Crunches",
 "Pendelay Rows",
 "Preacher Curls",
 "Push Press",
 "Reverse Plank",
 "Rowing, T-bar",
 "Shotgun Row",
 "Shrugs, Barbells",
 "Side Plank",
 "Sit-ups",
 "Splinter Sit-ups",
 "Stationary Bike",
 "Straight-arm Pull Down (rope Attachment)",
 "Triceps Dips",
 "Underhand Lat Pull Down",
 "Upright Row w/ Dumbbells",
 "Wall Squat",
 "Z Curls",
 "Barbell Hack Squats",
 "Pause Bench",
 "Pistol Squat",
 "Pull Ups on Machine",
 "Reverse Bar Curl",
 "Roman Chair",
 "Run - Interval Training ",
 "Shoulder Press, Barbell",
 "Side Crunch",
 "Side to Side Push Ups",
 "Smith Machine Close-grip Bench Press",
 "Standing Rope Forearm",
 "Superman",
 "Triceps Extensions on Cable With Bar",
 "Upper Body",
 "V-Bar Pulldown",
 "Weighted Step-ups",
 "Push Ups",
 "Reverse Grip Bench Press",
 "Rowing, Lying on Bench",
 "Seated Triceps Press",
 "Shoulder Press, on Machine",
 "Side-lying External Rotation",
 "Single-arm Preacher Curl",
 "Speed Deadlift",
 "Squats",
 "Stiff-legged Deadlifts",
 "Triceps Bench Press One Barbell",
 "Triceps Machine",
 "Upright Row, SZ-bar",
 "Weighted Step",
 "Rack Deadlift",
 "Ring Dips",
 "Rowing, Seated",
 "Run - Treadmill",
 "Shoulder Press, on Multi Press",
 "Side Dumbbell Trunk Flexion",
 "Sitting Calf Raises",
 "Snach",
 "Standing Calf Raises",
 "Straight-arm Pull Down (bar Attachment)",
 "Tricep Dumbbell Kickback",
 "Trunk Rotation With Cable ",
 "Upper External Oblique",
 "Wall Pushup",
 "Side Raise",
 "Skipping - Standard",
 "Squat Jumps",
 "Thruster",
 "Triceps Extensions on Cable",
 "Turkish Get-Up",
 "Upright Row, on Multi Press",
 "Wall Handstand",
 "Wide-grip Pulldown"
   ]


  export default AutoCompleteItems
